package com.attendance.util;

import com.attendance.database.DatabaseConnection;

import java.io.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Utility for performing SQL Database Backup and Restore operations.
 */
public class DBBackupUtil {

    public static boolean backupDatabase(File destFile) {
        try (Connection conn = DatabaseConnection.getConnection();
             FileWriter writer = new FileWriter(destFile)) {

            writer.write("-- Database Backup Generated by Attendance Management System\n");
            writer.write("-- Date: " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date()) + "\n\n");
            writer.write("CREATE DATABASE IF NOT EXISTS attendance_db;\n");
            writer.write("USE attendance_db;\n\n");

            String[] tables = {"admin", "subjects", "students", "attendance"};

            for (String table : tables) {
                exportTableData(conn, table, writer);
            }

            writer.flush();
            return true;
        } catch (Exception e) {
            System.err.println("Database Backup Error: " + e.getMessage());
            return false;
        }
    }

    private static void exportTableData(Connection conn, String tableName, FileWriter writer) throws SQLException, IOException {
        writer.write("-- Table Data: " + tableName + "\n");
        String query = "SELECT * FROM " + tableName;
        try (Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {

            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();

            while (rs.next()) {
                StringBuilder insertSql = new StringBuilder();
                insertSql.append("INSERT INTO ").append(tableName).append(" VALUES (");

                for (int i = 1; i <= columnCount; i++) {
                    Object val = rs.getObject(i);
                    if (val == null) {
                        insertSql.append("NULL");
                    } else if (val instanceof Number) {
                        insertSql.append(val);
                    } else {
                        insertSql.append("'").append(val.toString().replace("'", "''")).append("'");
                    }

                    if (i < columnCount) insertSql.append(", ");
                }
                insertSql.append(");\n");
                writer.write(insertSql.toString());
            }
            writer.write("\n");
        }
    }

    public static boolean restoreDatabase(File scriptFile) {
        try (Connection conn = DatabaseConnection.getConnection();
             BufferedReader reader = new BufferedReader(new FileReader(scriptFile));
             Statement stmt = conn.createStatement()) {

            StringBuilder sqlCommand = new StringBuilder();
            String line;

            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.startsWith("--") || line.startsWith("//") || line.isEmpty()) {
                    continue;
                }
                sqlCommand.append(line).append(" ");
                if (line.endsWith(";")) {
                    stmt.execute(sqlCommand.toString());
                    sqlCommand.setLength(0);
                }
            }
            return true;
        } catch (Exception e) {
            System.err.println("Database Restore Error: " + e.getMessage());
            return false;
        }
    }
}
